# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shorten_Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=250)),
                ('seller', models.CharField(max_length=250)),
                ('country', models.CharField(choices=[('us', '美国'), ('ca', '加拿大'), ('fr', '法国'), ('de', '德国'), ('it', '意大利'), ('jp', '日本'), ('es', '西班牙'), ('uk', '英国')], default='us', max_length=50)),
                ('keywords', models.TextField()),
                ('text', models.CharField(max_length=5000)),
                ('shorten_id', models.SlugField(max_length=6)),
                ('httpurl', models.URLField(max_length=2000)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='url', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
