# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('vote', models.PositiveIntegerField(default=0, null=True)),
                ('answer', models.CharField(max_length=1000, null=True)),
                ('answer_person', models.CharField(max_length=1000, null=True)),
                ('num', models.CharField(max_length=10, null=True)),
                ('answer_url', models.CharField(max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('qa_time', models.CharField(max_length=1000, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_detail', to='core.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Review_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('star', models.PositiveIntegerField()),
                ('customer_id', models.CharField(max_length=1000, null=True)),
                ('customer_url', models.CharField(max_length=1000, null=True)),
                ('review_time', models.CharField(max_length=1000)),
                ('review_text', models.CharField(max_length=10000, null=True)),
                ('review_chinese', models.CharField(max_length=10000, null=True)),
                ('normal', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_detail', to='core.Product')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
