# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-06 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_qa_collect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_detail',
            name='answer',
            field=models.CharField(max_length=15000, null=True),
        ),
        migrations.AlterField(
            model_name='qa_detail',
            name='question',
            field=models.CharField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='review_detail',
            name='review_chinese',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='review_detail',
            name='review_text',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
