# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-06 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_qa_collect', '0003_auto_20170806_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_detail',
            name='answer_url',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
