# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-06 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_qa_collect', '0004_auto_20170806_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_detail',
            name='answer_url',
            field=models.URLField(max_length=10000, null=True),
        ),
    ]
