# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_qa_collect', '0006_auto_20170806_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa_detail',
            name='answer_chinese',
            field=models.CharField(max_length=150000, null=True),
        ),
        migrations.AddField(
            model_name='qa_detail',
            name='question_chinese',
            field=models.CharField(max_length=80000, null=True),
        ),
    ]
