# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-09 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_qa_collect', '0007_auto_20170807_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_detail',
            name='vote',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
