# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 01:07
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=400)),
                ('asins_in', models.TextField()),
                ('title', models.CharField(max_length=5000)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('brand', models.CharField(max_length=500, null=True)),
                ('country', models.CharField(choices=[('us', '美国'), ('ca', '加拿大'), ('fr', '法国'), ('de', '德国'), ('it', '意大利'), ('jp', '日本'), ('es', '西班牙'), ('uk', '英国')], default='us', max_length=50)),
                ('img_url', models.URLField(max_length=5000, null=True)),
                ('detail_page_url', models.URLField(max_length=5000, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('re_qa_slug', models.SlugField(max_length=250, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=500, null=True)),
                ('bsr_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.CharField(max_length=2000)),
                ('review_qa', models.BooleanField(default=False)),
                ('detail', models.BooleanField(default=False)),
                ('review_qa_apply_time', models.DateTimeField(null=True)),
                ('review_qa_complete_time', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product_to_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('review_qa', models.BooleanField(default=False)),
                ('detail', models.BooleanField(default=False)),
                ('asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_to_User', to='core.Product')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_to_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
