# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asin_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_rank', models.IntegerField(blank=True, null=True, verbose_name='销售额排行')),
                ('sell_quant', models.IntegerField(blank=True, null=True, verbose_name='销售数量')),
                ('sell_amount', models.IntegerField(blank=True, null=True, verbose_name='销售额')),
                ('fu_sell_quant', models.IntegerField(blank=True, null=True, verbose_name='父体销售数量')),
                ('fu_sell_amout', models.IntegerField(blank=True, null=True, verbose_name='父体销售额')),
                ('prop', models.CharField(choices=[('us', '美国'), ('ca', '加拿大'), ('fr', '法国'), ('de', '德国'), ('it', '意大利'), ('jp', '日本'), ('es', '西班牙'), ('uk', '英国')], default='us', max_length=60, verbose_name='国别')),
                ('img_url', models.URLField(max_length=5000, null=True, verbose_name='图片')),
                ('detail_page_url', models.URLField(max_length=5000, null=True, verbose_name='网页')),
                ('price', models.CharField(max_length=50, null=True, verbose_name='价格')),
                ('brand', models.CharField(max_length=500, null=True, verbose_name='品牌')),
                ('label', models.CharField(max_length=500, null=True, verbose_name='标牌')),
                ('bsr_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='排名')),
                ('description', models.CharField(max_length=1000, verbose_name='描述')),
                ('asin', models.CharField(max_length=200, verbose_name='ASIN')),
                ('title', models.CharField(max_length=1000, verbose_name='标题')),
                ('fu_asin', models.CharField(max_length=200, verbose_name='父体ASIN')),
                ('fu_asin_title', models.CharField(max_length=1000, verbose_name='父体ASIN标题')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['description', 'sell_rank'],
            },
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/documents/')),
                ('name', models.CharField(max_length=500, verbose_name='文件名')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
