# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime_asins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asin_detail',
            old_name='prop',
            new_name='country',
        ),
    ]
