# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime_asins', '0002_auto_20170720_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asin_detail',
            name='asin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ASIN'),
        ),
        migrations.AlterField(
            model_name='asin_detail',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='asin_detail',
            name='fu_asin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='父体ASIN'),
        ),
        migrations.AlterField(
            model_name='asin_detail',
            name='fu_asin_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='父体ASIN标题'),
        ),
        migrations.AlterField(
            model_name='asin_detail',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='标题'),
        ),
    ]
