# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='target_text',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
