# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='glucose_high',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='glucose_low',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='glucose_target_max',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='glucose_target_min',
        ),
    ]
