# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170411_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='credit',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
