# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersettings_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='credit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
