# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170425_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='inventory_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='keyword_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='rank_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
