# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170524_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
