# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usersettings_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='inventory_count',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='keyword_count',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='rank_count',
        ),
    ]
