# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 02:59
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=redactor.fields.RedactorField(verbose_name='Text'),
        ),
    ]
