# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='asin',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='slug',
            field=models.SlugField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
