# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20170427_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='asin',
            field=models.CharField(max_length=100),
        ),
    ]
