# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20170428_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='country',
            field=models.CharField(choices=[('us', 'American'), ('ca', 'Canada'), ('fr', 'France'), ('de', 'Germany'), ('it', 'Italy'), ('jp', 'Japan'), ('es', 'Spain'), ('uk', 'United Kingdom')], default='us', max_length=50),
        ),
    ]
