# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='country',
            field=models.CharField(choices=[('us', '美国'), ('ca', '加拿大'), ('fr', '法国'), ('de', '德国'), ('it', '意大利'), ('jp', '日本'), ('es', '西班牙'), ('uk', '英国')], default='us', max_length=50),
        ),
    ]
