# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventory_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
