# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventory_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='img_url',
            field=models.URLField(default='http://chen-1252306246.cosgz.myqcloud.com/33754f47ab85497ea29176b9be84123f.jpg'),
            preserve_default=False,
        ),
    ]
