# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventory_img_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-created']},
        ),
    ]
