# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-08 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20170607_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory_time',
            options={'ordering': ['-date']},
        ),
    ]
