# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_inventory_detail_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='detail_page_url',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='img_url',
            field=models.URLField(max_length=5000),
        ),
    ]
