# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20170614_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_time',
            name='star',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
