# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_time',
            field=models.CharField(max_length=1000),
        ),
    ]
