# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review_monitor', '0002_auto_20170619_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_to_user',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review_to_user',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='expired',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Review_to_user',
        ),
    ]
