# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_monitor', '0003_auto_20170619_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.PositiveIntegerField(choices=[(1, '一星'), ('2', '一星'), ('3', '一星')], default=1),
        ),
    ]
