# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_monitor', '0005_auto_20170619_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
