# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_monitor', '0007_auto_20170619_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.PositiveIntegerField(choices=[(1, '1星'), (2, '2星和以下'), (3, '3星和以下')], default=1),
        ),
    ]
