# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_monitor', '0008_auto_20170621_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='customer_url',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
