# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asin_keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('ean', models.CharField(max_length=40)),
                ('keyword', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['asin'],
            },
        ),
    ]
