# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asin_keyword', '0003_auto_20170421_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='asin_keyword',
            name='country',
            field=models.CharField(choices=[('us', 'American'), ('ca', 'Canada'), ('fr', 'France'), ('de', 'Germany'), ('it', 'Italy'), ('jp', 'Japan'), ('es', 'Spain'), ('uk', 'United Kingdom')], default='us', max_length=50),
        ),
    ]
