# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asin_keyword', '0004_asin_keyword_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asin_keyword',
            name='keyword',
            field=models.CharField(max_length=5000),
        ),
    ]
