# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-08 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asin_keyword', '0007_asin_keyword_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='asin_keyword',
            name='img',
            field=models.URLField(default='http://www.amz668.com/static/images/icons/icon.jpg'),
            preserve_default=False,
        ),
    ]
