# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asin_keyword', '0009_auto_20170610_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asin_keyword',
            name='img',
            field=models.URLField(max_length=5000, null=True),
        ),
    ]
