# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asin_keyword', '0010_auto_20170612_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='asin_keyword',
            name='url',
            field=models.CharField(default='amz668.com/asin_keyword', max_length=5000),
            preserve_default=False,
        ),
    ]
