# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asin_keyword', '0011_asin_keyword_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asin_keyword',
            name='keyword',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
