# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='no_exist_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_exist_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ManyToManyField(blank=True, null=True, related_name='follow_sale_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
