# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follow_sale', '0002_auto_20170427_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_seller',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_seller', to='follow_sale.Product'),
        ),
    ]
