# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_sale', '0005_product_seller_mark_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_seller',
            name='mark_time',
        ),
    ]
