# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_sale', '0006_remove_product_seller_mark_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('us', 'American'), ('ca', 'Canada'), ('fr', 'France'), ('de', 'Germany'), ('it', 'Italy'), ('jp', 'Japan'), ('es', 'Spain'), ('uk', 'United Kingdom')], default='us', max_length=50),
        ),
    ]
