# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 03:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follow_sale', '0008_remove_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='follow_sale_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
