# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follow_sale', '0010_product_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('seller_id', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('old', 'old'), ('same', 'same')], default='new', max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='exist',
        ),
        migrations.RemoveField(
            model_name='product',
            name='no_exist_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='no_exist_time',
        ),
        migrations.AddField(
            model_name='seller_change',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_change', to='follow_sale.Product'),
        ),
    ]
