# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_sale', '0011_auto_20170512_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_seller',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product_seller',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='seller_change',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='seller_change',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('old', 'old')], default='new', max_length=10),
        ),
    ]
