# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_sale', '0014_auto_20170527_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
