# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_sale', '0015_remove_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(max_length=250),
        ),
    ]
