# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_sale', '0016_auto_20170606_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.URLField(default='http://www.amz668.com'),
            preserve_default=False,
        ),
    ]
