# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-08 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_sale', '0017_product_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_page_url',
            field=models.URLField(default='http://www.amz668.com/static/images/icons/icon.jpg'),
            preserve_default=False,
        ),
    ]
