# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_sale', '0018_product_detail_page_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_seller',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='seller_change',
            options={'ordering': ['-created']},
        ),
    ]
