# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_sale', '0016_auto_20170527_2220'),
        ('follow_sale', '0019_auto_20170609_1502'),
    ]

    operations = [
    ]
