# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword_rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=400)),
                ('title', models.CharField(max_length=5000)),
                ('country', models.CharField(choices=[('us', 'American'), ('ca', 'Canada'), ('fr', 'France'), ('de', 'Germany'), ('it', 'Italy'), ('jp', 'Japan'), ('es', 'Spain'), ('uk', 'United Kingdom')], default='us', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['asin'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_index', models.CharField(choices=[('Appliances', 'Appliances'), ('ArtsAndCrafts', 'ArtsAndCrafts'), ('Automotive', 'Automotive'), ('Baby', 'Baby'), ('Beauty', 'Beauty'), ('Books', 'Books'), ('Collectibles', 'Collectibles'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('FashionBaby', 'FashionBaby'), ('FashionBoys', 'FashionBoys'), ('FashionGirls', 'FashionGirls'), ('FashionMen', 'FashionMen'), ('FashionWomen', 'FashionWomen'), ('GiftCards', 'GiftCards'), ('Grocery', 'Grocery'), ('Handmade', 'Handmade'), ('HealthPersonalCare', 'HealthPersonalCare'), ('HomeGarden', 'HomeGarden'), ('Industrial', 'Industrial'), ('KindleStore', 'KindleStore'), ('LawnAndGarden', 'LawnAndGarden'), ('Luggage', 'Luggage'), ('Magazines', 'Magazines'), ('MobileApps', 'MobileApps'), ('Movies', 'Movies'), ('MP3Downloads', 'MP3Downloads'), ('Music', 'Music'), ('MusicalInstruments', 'MusicalInstruments'), ('OfficeProducts', 'OfficeProducts'), ('PCHardware', 'PCHardware'), ('PetSupplies', 'PetSupplies'), ('Software', 'Software'), ('SportingGoods', 'SportingGoods'), ('Tools', 'Tools'), ('Toys', 'Toys'), ('UnboxVideo', 'UnboxVideo'), ('Vehicles', 'Vehicles'), ('VideoGames', 'VideoGames'), ('Wine', 'Wine'), ('Wireless', 'Wireless'), ('All', 'All')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('word', models.CharField(max_length=5000, null=True)),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('keyword_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rank', to='keyword_rank.Keyword_rank')),
            ],
        ),
        migrations.CreateModel(
            name='Rank_to_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('expired', models.DateTimeField()),
                ('keyword_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rank_to_user', to='keyword_rank.Keyword_rank')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rank_to_user', to='keyword_rank.Rank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rank_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
