# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_rank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='search_index',
        ),
    ]
