# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 07:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_rank', '0002_remove_rank_search_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='keyword_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank', to='keyword_rank.Keyword_rank'),
        ),
        migrations.AlterField(
            model_name='rank_to_user',
            name='keyword_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_to_user', to='keyword_rank.Keyword_rank'),
        ),
        migrations.AlterField(
            model_name='rank_to_user',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_to_user', to='keyword_rank.Rank'),
        ),
        migrations.AlterField(
            model_name='rank_to_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
