# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_rank', '0004_auto_20170512_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='word',
        ),
        migrations.RemoveField(
            model_name='rank_to_user',
            name='rank',
        ),
        migrations.AddField(
            model_name='keyword_rank',
            name='word',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
