# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_rank', '0005_auto_20170523_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword_rank',
            name='text',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
