# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_rank', '0006_keyword_rank_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
