# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_rank', '0007_rank_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword_rank',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='keyword_rank',
            name='detail_page_url',
            field=models.URLField(default='http://www.amz668.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword_rank',
            name='img_url',
            field=models.URLField(default='http://www.amz668.com/static/images/icons/icon.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword_rank',
            name='rank_url',
            field=models.URLField(default='http://www.amz668.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rank',
            name='text',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
