# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-12 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_rank', '0008_auto_20170609_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword_rank',
            name='detail_page_url',
            field=models.URLField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='keyword_rank',
            name='img_url',
            field=models.URLField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='keyword_rank',
            name='rank_url',
            field=models.URLField(max_length=5000, null=True),
        ),
    ]
