# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_rank', '0011_remove_rank_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
