# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='In_word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_word', models.CharField(max_length=1000)),
                ('country', models.CharField(choices=[('us', '美国'), ('ca', '加拿大'), ('fr', '法国'), ('de', '德国'), ('it', '意大利'), ('jp', '日本'), ('es', '西班牙'), ('uk', '英国')], default='us', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Out_word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_word', models.CharField(max_length=1000)),
                ('in_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_word', to='rele_keyword.In_word')),
            ],
        ),
    ]
